# Flask settings
DEBUG = True
DEVELOPMENT = True
SECRET_KEY = 'do-i-really-need-this'
SQLALCHEMY_DATABASE_URI = 'sqlite:///hydrolab_db/hydrolab.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SMTP_PASSWORD = ''
SMTP_USERNAME = 'ericroyalmonacid@gmail.com'
GOOGLE_AUTH_FILE_ABSOLUTE_PATH = ''
