# Flask settings
DEBUG = False
DEVELOPMENT = False
SECRET_KEY = 'please-change-this-in-prod'
SQLALCHEMY_DATABASE_URI = 'sqlite:///hydrolab_db/hydrolab.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SMTP_PASSWORD = ''
SMTP_USERNAME = 'ericroyalmonacid@gmail.com'
GOOGLE_AUTH_FILE_ABSOLUTE_PATH = ''
WEATHER_API_KEY = ''
